---
kind: pipeline
type: docker
name: default

## 禁止默認 clone 行為
clone:
  disable: true

steps:
  - name: host
    image: alpine
    commands:
      - cat /etc/hosts
    when:
      status: [ success, failure ]

  - name: docker
    image: plugins/docker
    settings:
      registry: hub.docker.com
      repo: https://github.com/joshku01/golang-test-cicd
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username: joshku01
      password:
        from_secret: docker_password
## 觸發 pipeline 條件
trigger:
  branch:
    - main
  event:
    - push
