---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang:1.16-alpine
    commands:
      - "go test"

  - name: docker
    image: plugins/docker
    settings:
      registry: hub.docker.com
      repo: https://github.com/joshku01/golang-test-cicd
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username: joshku01
      password:
        from_secret: docker_password
## 觸發 pipeline 條件
trigger:
  branch:
    - main
