kind: pipeline
type: docker
name: default

## 禁止默認 clone 行為
clone:
  disable: true

steps:
  - name: build
    image: golang:1.16.7
    commands:
      - make build_linux_amd64

  - name: docker
    image: plugins/docker
    settings:
      registry: hub.docker.com
      repo: https://github.com/joshku01/golang-test-cicd
      auto_tag: true
      auto_tag_suffix: linux-amd64
      username: joshku01
      password:
        from_secret: docker_password
## 觸發 pipeline 條件
trigger:
  ref:
    include:
      - refs/heads/main
      - refs/heads/develop
      - refs/heads/qatest
      - refs/heads/int
      - refs/tags/v*
      - refs/tags/t*
